const getConstants = () => {
    return {
        API_URL : process.env.NODE_ENV === "development" ? "https://vizion-api-t8wzz.ondigitalocean.app/api" : "https://vizion-api-t8wzz.ondigitalocean.app/api",
        MAPBOX_TOKEN : "pk.eyJ1IjoiY29yZS12aXppb24iLCJhIjoiY20ycGQ4b2dwMHQ1cjJrb204a25iZHR3cyJ9.Z5XS7M19N8FcGHahQ9dgiw",
        REGIMES : [
            { "name": "General de Ley Personas Morales", "value": "601", "type": "enterprise" },
            { "name": "Personas Morales con Fines no Lucrativos", "value": "603", "type": "enterprise" },
            { "name": "Sueldos y Salarios e Ingresos Asimilados a Salarios", "value": "605", "type": "particular" },
            { "name": "Arrendamiento", "value": "606", "type": "particular" },
            { "name": "Régimen de Enajenación o Adquisición de Bienes", "value": "607", "type": "particular" },
            { "name": "Demás ingresos", "value": "608", "type": "particular" },
            { "name": "Ingresos por Dividendos (socios y accionistas)", "value": "611", "type": "particular" },
            { "name": "Personas Físicas con Actividades Empresariales y Profesionales", "value": "612", "type": "particular" },
            { "name": "Ingresos por intereses", "value": "614", "type": "particular" },
            { "name": "Régimen de los ingresos por obtención de premios", "value": "615", "type": "particular" },
            { "name": "Sociedades Cooperativas de Producción que optan por diferir sus ingresos", "value": "620", "type": "enterprise" },
            { "name": "Incorporación Fiscal", "value": "621", "type": "particular" },
            { "name": "Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras", "value": "622", "type": "enterprise" },
            { "name": "Opcional para Grupos de Sociedades", "value": "623", "type": "enterprise" },
            { "name": "Coordinados", "value": "624", "type": "enterprise" },
            { "name": "Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas", "value": "625", "type": "particular" },
            { "name": "Régimen Simplificado de Confianza", "value": "626", "type": "both" }
        ],
        PAYMENT_FORMS : [
          { "name": "Efectivo", "value": "01" },
          { "name": "Cheque nominativo", "value": "02" },
          { "name": "Transferencia electrónica de fondos", "value": "03" },
          { "name": "Tarjeta de crédito", "value": "04" },
          { "name": "Monedero electrónico", "value": "05" },
          { "name": "Dinero electrónico", "value": "06" },
          { "name": "Vales de despensa", "value": "08" },
          { "name": "Dación en pago", "value": "12" },
          { "name": "Pago por subrogación", "value": "13" },
          { "name": "Pago por consignación", "value": "14" },
          { "name": "Condonación", "value": "15" },
          { "name": "Compensación", "value": "17" },
          { "name": "Novación", "value": "23" },
          { "name": "Confusión", "value": "24" },
          { "name": "Remisión de deuda", "value": "25" },
          { "name": "Prescripción o caducidad", "value": "26" },
          { "name": "A satisfacción del acreedor", "value": "27" },
          { "name": "Tarjeta de débito", "value": "28" },
          { "name": "Tarjeta de servicios", "value": "29" },
          { "name": "Aplicación de anticipos", "value": "30" },
          { "name": "Por definir", "value": "99" }
        ],
        PAYMENT_METHODS : [
          { "name" : "Pago en una sola exhibición", "value" : "PUE" },
          { "name" : "Pago en parcialidades o diferido", "value" : "PPD" }
        ],
        CFDI_USE : [
          { "name": "Adquisición de mercancías", "value": "G01" },
          { "name": "Devoluciones, descuentos o bonificaciones", "value": "G02" },
          { "name": "Gastos en general", "value": "G03" },
          { "name": "Construcciones", "value": "I01" },
          { "name": "Mobiliario y equipo de oficina por inversiones", "value": "I02" },
          { "name": "Equipo de transporte", "value": "I03" },
          { "name": "Equipo de cómputo y accesorios", "value": "I04" },
          { "name": "Dados, troqueles, moldes, matrices y herramental", "value": "I05" },
          { "name": "Comunicaciones telefónicas", "value": "I06" },
          { "name": "Comunicaciones satelitales", "value": "I07" },
          { "name": "Otra maquinaria y equipo", "value": "I08" },
          { "name": "Honorarios médicos, dentales y gastos hospitalarios", "value": "D01" },
          { "name": "Gastos médicos por incapacidad o discapacidad", "value": "D02" },
          { "name": "Gastos funerales", "value": "D03" },
          { "name": "Donativos", "value": "D04" },
          { "name": "Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)", "value": "D05" },
          { "name": "Aportaciones voluntarias al SAR", "value": "D06" },
          { "name": "Primas por seguros de gastos médicos", "value": "D07" },
          { "name": "Gastos de transportación escolar obligatorio", "value": "D08" },
          { "name": "Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones", "value": "D09" },
          { "name": "Pagos por servicios educativos (colegiaturas)", "value": "D10" },
          { "name": "Sin efectos fiscales", "value": "S01" },
          { "name": "Pagos", "value": "CP01" },
          { "name": "Nómina", "value": "CN01" }
        ],
        PAYMENT_TERMS : [
          { "name" : "Sin Definir", "value" : "undefined" },
          { "name" : "Pago Anticipado", "value" : "anticipated" },
          { "name" : "Pago contra Entrega", "value" : "on-deliver" },
          { "name" : "Anticipo y Liquidación", "value" : "on-advance"},
          { "name" : "Crédito", "value" : "credit"},
        ],
        IVA_TAXES : [
          { "name": "Exento de IVA", "value": "-1" },
          { "name": "IVA - 0%", "value": "0" },
          { "name": "IVA - 8%", "value": "8" },
          { "name": "IVA - 16%", "value": "16" },
        ],
    };
};

export default getConstants;